services:
  mysql:
    image: mysql:8.4.5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metastore
    ports:
      - "3307:3306"
    networks:
      - reddit_network


  hive_service:
    build:
      context: ../..
      dockerfile: docker/hive_metastore/dockerfile
    container_name: hive_service
    hostname: hive_service
    ports:
      - "9083:9083"
    depends_on:
      - mysql
    environment:
      HIVE_METASTORE_DB_TYPE: mysql
      HIVE_METASTORE_DB_HOST: mysql
      HIVE_METASTORE_DB_PORT: 3306
      HIVE_METASTORE_DB_NAME: metastore
      HIVE_METASTORE_DB_USER: root
      HIVE_METASTORE_DB_PASSWORD: root
    networks:
      - reddit_network
networks:
  reddit_network:
    driver: bridge
    name: reddit_network
    external: true 
