services:
  trino-coordinator:
    image: trinodb/trino:423
    container_name: trino-coordinator
    hostname: trino-coordinator
    ports:
      - "8081:8080"
    volumes:
      - ../..config/trino/coordinator/etc:/etc/trino
    networks:
      - data_network
    environment:
      - HIVE_METASTORE_SERVER=hive_service

  trino-worker-1:
    image: trinodb/trino:423
    container_name: trino-worker-1
    hostname: trino-worker-1
    volumes:
      - ../..config/trino/worker1/etc:/etc/trino
    networks:
      - data_network
    environment:
      - HIVE_METASTORE_SERVER=hive_service

  trino-worker-2:
    image: trinodb/trino:423
    container_name: trino-worker-2
    hostname: trino-worker-2
    volumes:
      - ../..config/trino/worker2/etc:/etc/trino
    networks:
      - data_network
    environment:
      - HIVE_METASTORE_SERVER=hive_service

networks:
  data_network:
    external: true
