version: '3.8'

services:
  trino-coordinator:
    image: trino-with-s3a
    container_name: trino-coordinator
    hostname: trino-coordinator
    ports:
      - "8081:8080"
    volumes:
      - ./trino/coordinator/etc:/etc/trino
    networks:
      - data_network


  trino-worker-1:
    image: trinodb/trino:423
    container_name: trino-worker-1
    hostname: trino-worker-1
    volumes:
      - ./trino/worker1/etc:/etc/trino
    networks:
      - data_network

  trino-worker-2:
    image: trinodb/trino:423
    container_name: trino-worker-2
    hostname: trino-worker-2
    volumes:
      - ./trino/worker2/etc:/etc/trino
    networks:
      - data_network


networks:
  data_network:
    external: true
