services:
  minio1:
    image: bitnami/minio:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=mypassword
    container_name: minio1
    networks:
      - reddit_network
    user: root 
    volumes:
      - minio1_data:/bitnami/minio/data
      - minio1_certs:/certs


  minio_client:
    image: bitnami/minio-client:latest
    depends_on:
      - minio1
    entrypoint: >
      /bin/sh -c "sleep 10 && mc alias set minio http://minio1:9000 minio mypassword && mc mb minio/lakehouse && mc mb minio/checkpoint && tail -F anything"
    networks:
      - reddit_network

volumes:
  minio1_data:
  minio1_certs:

networks:
  reddit_network:
    driver: bridge
    name: reddit_network
    external: true 